// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Database.EntityFrameworkCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies.Database.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20240417083251_Add_Movies_Table")]
    partial class Add_Movies_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Movies.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.HasIndex("Genres");

                    b.HasIndex("Key");

                    b.HasIndex("Rate");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A former Special Forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers, adopting the alter ego Deadpool.",
                            Genres = "[1,2,3]",
                            Img = "deadpool.jpg",
                            Key = "deadpool",
                            Length = "1hr 48mins",
                            Name = "Deadpool",
                            Rate = 8.6m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A veteran pot dealer creates a fake family as part of his plan to move a huge shipment of weed into the U.S. from Mexico.",
                            Genres = "[2,3,4]",
                            Img = "we-are-the-millers.jpg",
                            Key = "we-are-the-millers",
                            Length = "1hr 50mins",
                            Name = "We're the Millers",
                            Rate = 7.0m
                        },
                        new
                        {
                            Id = 3,
                            Description = "The group NWA emerges from the mean streets of Compton in Los Angeles, California, in the mid-1980s and revolutionizes Hip Hop culture with their music and tales about life in the hood.",
                            Genres = "[5,6,7]",
                            Img = "straight-outta-compton.jpg",
                            Key = "straight-outta-compton",
                            Length = "2hr 27mins",
                            Name = "Straight Outta Compton",
                            Rate = 8.0m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Teenagers at a juvenile detention center, under the leadership of their counselor, gain self-esteem by playing football together.",
                            Genres = "[4,6,8]",
                            Img = "gridiron-gang.jpg",
                            Key = "gridiron-gang",
                            Length = "2hr 5mins",
                            Name = "Gridiron Gang",
                            Rate = 6.9m
                        },
                        new
                        {
                            Id = 5,
                            Description = "In 1970s America, a detective works to bring down the drug empire of Frank Lucas, a heroin kingpin from Manhattan, who is smuggling the drug into the country from the Far East.",
                            Genres = "[5,4,6]",
                            Img = "american-gangster.jpg",
                            Key = "american-gangster",
                            Length = "2hr 37mins",
                            Name = "American Gangster",
                            Rate = 7.8m
                        },
                        new
                        {
                            Id = 6,
                            Description = "It's 1949 Los Angeles, the city is run by gangsters and a malicious mobster, Mickey Cohen. Determined to end the corruption, John O'Mara assembles a team of cops, ready to take down the ruthless leader and restore peace to the city.",
                            Genres = "[1,4,6]",
                            Img = "gangster-squad.jpg",
                            Key = "gangster-squad",
                            Length = "1hr 53mins",
                            Name = "Gangster Squad",
                            Rate = 6.8m
                        },
                        new
                        {
                            Id = 7,
                            Description = "An FBI agent and an Interpol detective track a team of illusionists who pull off bank heists during their performances and reward their audiences with the money.",
                            Genres = "[4,9,10]",
                            Img = "now-you-see-me.jpg",
                            Key = "now-you-see-me",
                            Length = "1hr 55mins",
                            Name = "Now You See Me",
                            Rate = 7.3m
                        },
                        new
                        {
                            Id = 8,
                            Description = "A new theme park is built on the original site of Jurassic Park. Everything is going well until the park's newest attraction--a genetically modified giant stealth killing machine--escapes containment and goes on a killing spree.",
                            Genres = "[1,2,11]",
                            Img = "jurassic-world.jpg",
                            Key = "jurassic-world",
                            Length = "2hr 4mins",
                            Name = "Jurassic World",
                            Rate = 7.1m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Ethan and team take on their most impossible mission yet, eradicating the Syndicate - an International rogue organization as highly skilled as they are, committed to destroying the IMF.",
                            Genres = "[1,2,10]",
                            Img = "mission-impossible-rogue-nation.jpg",
                            Key = "mission-impossible-rogue-nation",
                            Length = "2hr 11mins",
                            Name = "Mission: Impossible: Rogue Nation",
                            Rate = 7.5m
                        },
                        new
                        {
                            Id = 10,
                            Description = "In the early 1960s, CIA agent Napoleon Solo and KGB operative Illya Kuryakin participate in a joint mission against a mysterious criminal organization, which is working to proliferate nuclear weapons.",
                            Genres = "[1,2,10]",
                            Img = "the-man-from-uncle.jpg",
                            Key = "the-man-from-uncle",
                            Length = "1hr 56mins",
                            Name = "The Man from U.N.C.L.E.",
                            Rate = 7.3m
                        },
                        new
                        {
                            Id = 11,
                            Description = "A cryptic message from Bond's past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
                            Genres = "[1,2,10]",
                            Img = "spectre.jpg",
                            Key = "spectre",
                            Length = "2hr 28mins",
                            Name = "Spectre",
                            Rate = 6.9m
                        },
                        new
                        {
                            Id = 12,
                            Description = "The film tells the story of the identical twin gangsters Reggie and Ronnie Kray, two of the most notorious criminals in British history, and their organised crime empire in the East End of London during the 1960s.",
                            Genres = "[5,4,6]",
                            Img = "legend.jpg",
                            Key = "legend",
                            Length = "2hr 28mins",
                            Name = "Legend",
                            Rate = 7.0m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Boxer Billy Hope turns to trainer Tick Wills to help him get his life back on track after losing his wife in a tragic accident and his daughter to child protection services.",
                            Genres = "[1,6,8]",
                            Img = "southpaw.jpg",
                            Key = "southpaw",
                            Length = "2hr 4mins",
                            Name = "Southpaw",
                            Rate = 7.5m
                        },
                        new
                        {
                            Id = 14,
                            Description = "During the Cold War, an American lawyer is recruited to defend an arrested Soviet spy in court, and then help the CIA facilitate an exchange of the spy for the Soviet captured American U2 spy plane pilot, Francis Gary Powers.",
                            Genres = "[5,6,10]",
                            Img = "bridge-of-spies.jpg",
                            Key = "bridge-of-spies",
                            Length = "2hr 22mins",
                            Name = "Bridge of Spies",
                            Rate = 7.7m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.",
                            Genres = "[1,2,11]",
                            Img = "ant-man.jpg",
                            Key = "ant-man",
                            Length = "1hr 57mins",
                            Name = "Ant-Man",
                            Rate = 7.4m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
                            Genres = "[1,4,10]",
                            Img = "fast-and-furious-7.jpg",
                            Key = "fast-and-furious-7",
                            Length = "2hr 17mins",
                            Name = "Fast & Furious 7",
                            Rate = 7.3m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Wanted by the Chinese mafia, a New York City bike messenger escapes into the world of parkour after meeting a beautiful stranger.",
                            Genres = "[1,4,6]",
                            Img = "tracers.jpg",
                            Key = "tracers",
                            Length = "1hr 34mins",
                            Name = "Tracers",
                            Rate = 5.6m
                        },
                        new
                        {
                            Id = 18,
                            Description = "A low-ranking thug is entrusted by his crime boss to dispose of a gun that killed corrupt cops, but things get out of control when the gun ends up in wrong hands.",
                            Genres = "[1,4,6]",
                            Img = "running-scared.jpg",
                            Key = "running-scared",
                            Length = "2hr 2mins",
                            Name = "Running Scared",
                            Rate = 7.4m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.",
                            Genres = "[3]",
                            Img = "the-hangover.jpg",
                            Key = "the-hangover",
                            Length = "1hr 40mins",
                            Name = "The Hangover",
                            Rate = 7.8m
                        },
                        new
                        {
                            Id = 20,
                            Description = "3 high school seniors throw a birthday party to make a name for themselves. As the night progresses, things spiral out of control as word of the party spreads.",
                            Genres = "[3,4]",
                            Img = "project-x.jpg",
                            Key = "project-x",
                            Length = "1hr 28mins",
                            Name = "Project X",
                            Rate = 6.7m
                        },
                        new
                        {
                            Id = 21,
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.",
                            Genres = "[1,4,6]",
                            Img = "the-dark-knight.jpg",
                            Key = "the-dark-knight",
                            Length = "2hr 32mins",
                            Name = "The Dark Knight",
                            Rate = 9.0m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Every seven years in an unsuspecting town, The Tournament takes place. A battle royale between 30 of the world's deadliest assassins. The last man standing receiving the $10,            000,            000 cash prize and the title of Worlds No 1, which itself carries the legendary million dollar a bullet price tag.",
                            Genres = "[1,10]",
                            Img = "the-tournament.jpg",
                            Key = "the-tournament",
                            Length = "1hr 35mins",
                            Name = "The Tournament",
                            Rate = 6.1m
                        },
                        new
                        {
                            Id = 23,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            Genres = "[1,11]",
                            Img = "the-matrix.jpg",
                            Key = "the-matrix",
                            Length = "2hr 16mins",
                            Name = "The Matrix",
                            Rate = 8.7m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Two hip detectives protect a murder witness while investigating a case of stolen heroin.",
                            Genres = "[1,3,4]",
                            Img = "bad-boys.jpg",
                            Key = "bad-boys",
                            Length = "1hr 59mins",
                            Name = "Bad Boys",
                            Rate = 6.8m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
